apiVersion: apps/v1
kind: Deployment
metadata:
  name: exceptions
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sbdemo
          resources:
            limits:
              cpu: 1
              memory: 1250Mi
            requests:
              cpu: 25m
              memory: 1250Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory